import comp from "D:/fo/vuepress-theme-hope/my-docs/src/.vuepress/.temp/pages/index.html.vue"
const data = JSON.parse("{\"path\":\"/\",\"title\":\"麦芽糖bot\",\"lang\":\"zh-CN\",\"frontmatter\":{\"home\":true,\"icon\":\"robot\",\"title\":\"麦芽糖bot\",\"heroImage\":\"/logotxt.png\",\"bgImage\":\"https://theme-hope-assets.vuejs.press/bg/6-light.svg\",\"bgImageDark\":\"https://theme-hope-assets.vuejs.press/bg/6-dark.svg\",\"bgImageStyle\":{\"background-attachment\":\"fixed\"},\"heroText\":\"‬\",\"tagline\":\"已部署的多功能QQ机器人，24小时在线为您服务\",\"features\":[{\"title\":\"机器人QQ号\",\"details\":3929982192,\"icon\":\"user\"},{\"title\":\"官方群\",\"details\":1030501081,\"icon\":\"comment\"},{\"title\":\"开箱即用\",\"details\":\"无需部署配置，添加好友即可使用\",\"icon\":\"plug\"},{\"title\":\"丰富功能\",\"details\":\"娱乐、工具、群管等多种功能\",\"icon\":\"gamepad\"},{\"title\":\"完全免费\",\"details\":\"永久免费使用\",\"icon\":\"gift\"},{\"title\":\"24小时在线\",\"details\":\"全天候运行，随时为您服务\",\"icon\":\"clock\"},{\"title\":\"持续更新\",\"details\":\"定期更新功能，优化用户体验\",\"icon\":\"arrow-up\"},{\"title\":\"不稳定不可靠\",\"details\":\"低性能服务器保障，运行不稳定不流畅\",\"icon\":\"shield\"},{\"title\":\"无技术支持\",\"details\":\"没有人提供及时的技术支持服务\",\"icon\":\"ban\"}],\"actions\":[{\"text\":\"立即使用\",\"icon\":\"rocket\",\"link\":\"./quick-start\",\"type\":\"primary\"},{\"text\":\"查看功能\",\"icon\":\"list-check\",\"link\":\"./features\"},{\"text\":\"部署配置\",\"icon\":\"book\",\"link\":\"./部署配置/\"}],\"description\":\"🚧 文档正在建设中 本文档目前仍在完善中，部分功能说明可能不够详细或存在遗漏。如果您在使用过程中遇到问题，欢迎在官方QQ群中反馈！\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"麦芽糖bot\\\",\\\"description\\\":\\\"🚧 文档正在建设中 本文档目前仍在完善中，部分功能说明可能不够详细或存在遗漏。如果您在使用过程中遇到问题，欢迎在官方QQ群中反馈！\\\"}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://maltose-bot.com/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"麦芽糖\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"麦芽糖bot\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🚧 文档正在建设中 本文档目前仍在完善中，部分功能说明可能不够详细或存在遗漏。如果您在使用过程中遇到问题，欢迎在官方QQ群中反馈！\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"readingTime\":{\"minutes\":1.03,\"words\":310},\"filePathRelative\":\"README.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
